### PR TITLE
Added a link to the Ghost-Updater-Azure project

### PR DESCRIPTION
**Pull request by markau**
I was wondering how to update the version of Ghost on Azure, and nearly sent Felix an email, when I discovered his related project. Having this in the readme might save you subsequent emails :smile:

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thanks a lot for the contribution! Hey, sadly, this isn't even the best way to update if you installed using this repo. There's a small "Sync" button which automatically pulls down changes in this repo, essentially automating what the updater is doing more or less manually.

Clearly, I should document that though. I'll put something in now.

**Comment by markau** [comment]
Thanks Felix. I should have looked more closely for the sync, as the update broke my install. I had exported the data fortunately. 

Do you know if I can use this method to install a fresh copy to the same Azure web app so I don't have to setup the domain name and ssl cert for a new web app? Thought it was worth asking :)

**Comment by felixrieseberg** [comment]
Deploy to Azure always creates a new app, _but_ you could just fork the repo and use Azure's GitHub connection to automatically deploy from your GitHub fork. In the management portal, select "Set up deployment from source control", then GitHub, and your fork. Voila!

**Comment by TerribleDev** [comment]
I fork off of this and I have commits that add themes and what not...when there are updates I just rebase off of this repo and then force push to my fork and then azure picks up on the new version (listening to my git repo) and deploys...

that seems easier than anything.

**Comment by markau** [comment]
Good idea, @felixrieseberg; that worked perfectly. Cheers!

@tparnell8 I'll look into your suggestion, thanks.

**Pull request merged**
